#!/usr/bin/env python3

from git import Repo

repo = Repo(".")

if repo.active_branch.name == "master":
    with open("illum/__init__.py") as f:
        content = f.read()
    line = content.split("\n")[0]
    version = line.split("=")[1].strip().strip("\"'")

    parts = version.split(".")[:3]
    parts[2] = str(int(parts[2]) + 1)

    with open("illum/__init__.py", "w") as f:
        f.write(content.replace(version, ".".join(parts)))
    repo.git.add("illum/__init__.py")
