[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-magic-trailing-comma = true
preview = true
target-version = ["py310"]

[tool.isort]
known_first_party = ['illum']
